name: flutter_ai_toolkit
description: >-
  AI chat widget for Flutter apps targeting mobile, desktop, and web supporting
  text, image, and voice input.
version: 1.0.0
repository: https://github.com/flutter/ai

topics:
  - ai
  - chat
  - gemini

environment:
  sdk: ^3.7.0
  flutter: ">=3.27.0"

dependencies:
  cross_file: ^0.3.4+2
  file_selector: ^1.0.3
  firebase_ai: ^3.0.0
  flutter:
    sdk: flutter
  flutter_context_menu: ^0.4.0
  flutter_markdown_plus: ^1.0.3
  flutter_picture_taker: ^0.2.0
  google_fonts: ^8.0.2
  image_picker: ^1.1.2
  mime: ^2.0.0
  universal_platform: ^1.1.0
  url_launcher: ^6.3.2
  uuid: ^4.4.2
  waveform_recorder: ^1.8.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: FatIcons
      fonts:
        - asset: lib/fonts/FatIcons.ttf
