// File normally generated by FlutterFire CLI. This is a stand-in.
// See README.md for details.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  // TODO: Remove this file and run `flutterfire config` for Firebase options
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError(
      'Generate this file by running `flutterfire configure`. '
      'See README.md for details.',
    );
  }
}
